name: Documentation
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.9"
        enable-cache: true

    - name: Install dependencies
      run: |
        uv sync --extra dev
        git config --global user.email "alexandre.defossez@gmail.com"
        git config --global user.name "Alexandre Défossez (autodoc)"

    - name: Reset branch
      run: |
        git branch -f gh-docs main
        git checkout gh-docs

    - name: Make docs
      run: |
        uv run --extra dev make docs
        git add -f docs
        git commit -m docs

    - name: Push branch
      run: |
        git push -f -u origin gh-docs
