name: linter
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: astral-sh/setup-uv@v6
      with:
        python-version: "3.9"
        enable-cache: true

    - name: Install dependencies
      run: uv sync --extra dev

    - name: Run linter
      run: uv run --extra dev make linter
